
[[constant]]
enum_name = "Pi"
strings = ["π", "pi"]
value = "3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067"

[[constant]]
enum_name = "Phi"
strings = ["φ", "phi"]
value = "1.618033988749894848204586834365638117720309179805762862135448622705260462818902449707207204189391137"

[[constant]]
enum_name = "Euler"
strings = "e"
value = "2.718281828459045235360287471352662497757247093699959574966967627724076630353547594571382178525166427"

[[constant]]
enum_name = "MPG"
strings = "mpg"
value = "mile/gallon"
unit = true


[[constant]]
enum_name = "MPH"
strings = "mph"
value = "mile/hour"
unit = true

[[constant]]
enum_name = "DPI"
strings = "dpi"
value = "dot/inch"
unit = true

[[constant]]
enum_name = "PPI"
strings = "ppi"
value = "pixel/inch"
unit = true

[[constant]]
enum_name = "FPS"
strings = "fps"
value = "frame/second"
unit = true

[[constant]]
enum_name = "PCT"
strings = "pct"
value = "0.01"
unit = true

[[constant]]
enum_name = "PPM"
strings = "ppm"
value = "1e-6"
unit = true

[[constant]]
enum_name = "PPB"
strings = "ppb"
value = "1e-9"
unit = true

[[constant]]
enum_name = "PPT"
strings = "ppt"
value = "1e-12"
unit = true

[[constant]]
enum_name = "PPQ"
strings = "ppq"
value = "1e-15"
unit = true

[[constant]]
enum_name = "KWH"
strings = "kWh"
value = "kW * hour"
unit = true

[[constant]]
enum_name = "MWH"
strings = "WMh"
value = "MW * hour"
unit = true

[[constant]]
enum_name = "GWH"
strings = "GWh"
value = "GW * hour"
unit = true

[[constant]]
enum_name = "TWH"
strings = "TWh"
value = "TW * hour"
unit = true

[[constant]]
enum_name = "PWH"
strings = "PWh"
value = "PW * hour"
unit = true