name: CI

on: [push]


jobs:
  build_and_test:
    name: Daisy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update toolchain
        run: |
          rustup update
          rustup install stable

      - name: Status
        run: |
          cargo --version --verbose
          rustc --version

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          cargo build --release